//go:build ignore

// Generate versioned normalization and HFS comparison tables from pinned sources.
package main

import (
	"bufio"
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

var check = flag.Bool("check", false, "verify committed tables without writing")

const primary = "testdata/appledouble/native/name-comparison-source"

func must(e error) {
	if e != nil {
		panic(e)
	}
}
func read(p string) []byte {
	b, e := os.ReadFile(p)
	must(e)
	if strings.HasSuffix(p, ".gz") {
		z, e := gzip.NewReader(bytes.NewReader(b))
		must(e)
		b, e = io.ReadAll(z)
		must(e)
		must(z.Close())
	}
	return b
}
func parse(s string) rune { v, e := strconv.ParseInt(s, 16, 32); must(e); return rune(v) }
func main() {
	flag.Parse()
	var manifest struct {
		Sources []struct{ File, SHA256 string }
	}
	for _, dir := range []string{primary, "testdata/appledouble/native/name-collation-source"} {
		must(json.Unmarshal(read(dir+"/sources.json"), &manifest))
		for _, source := range manifest.Sources {
			h := sha256.Sum256(read(filepath.Join(dir, source.File)))
			if hex.EncodeToString(h[:]) != source.SHA256 {
				panic("source hash " + source.File)
			}
		}
	}
	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by scripts/generate-name-tables.go. DO NOT EDIT.\n// Unicode data license: testdata/appledouble/native/name-comparison-source/LICENSE.txt\npackage nameunicode")
	for _, p := range []struct {
		name, path string
		hfs        bool
	}{{"apfs", "testdata/appledouble/native/name-collation-source/UnicodeData.txt.gz", false}, {"hfs", primary + "/UnicodeData-3.2.0.txt.gz", true}} {
		ds := map[rune]string{}
		cs := map[rune]int{}
		s := bufio.NewScanner(bytes.NewReader(read(p.path)))
		for s.Scan() {
			f := strings.Split(s.Text(), ";")
			r := parse(f[0])
			if p.hfs && r > 65535 {
				continue
			}
			n, e := strconv.Atoi(f[3])
			must(e)
			if n != 0 {
				cs[r] = n
			}
			if f[5] != "" && !strings.HasPrefix(f[5], "<") && !(p.hfs && ((r >= 0x2000 && r <= 0x2fff) || (r >= 0xf900 && r <= 0xfaff))) {
				var rs []rune
				for _, x := range strings.Fields(f[5]) {
					rs = append(rs, parse(x))
				}
				ds[r] = string(rs)
			}
		}
		must(s.Err())
		writeMap(&out, p.name+"Decompose", ds)
		fmt.Fprintf(&out, "var %sClass = map[rune]uint8{\n", p.name)
		for _, r := range keys(cs) {
			fmt.Fprintf(&out, "0x%X:%d,\n", r, cs[r])
		}
		fmt.Fprintln(&out, "}")
	}
	fold := map[rune]string{}
	s := bufio.NewScanner(bytes.NewReader(read("testdata/appledouble/native/name-collation-source/CaseFolding.txt.gz")))
	for s.Scan() {
		line, _, _ := strings.Cut(s.Text(), "#")
		if strings.TrimSpace(line) == "" {
			continue
		}
		f := strings.Split(line, ";")
		if st := strings.TrimSpace(f[1]); st == "C" || st == "F" {
			var rs []rune
			for _, x := range strings.Fields(f[2]) {
				rs = append(rs, parse(x))
			}
			fold[parse(strings.TrimSpace(f[0]))] = string(rs)
		}
	}
	must(s.Err())
	writeMap(&out, "apfsFold", fold)
	write("internal/nameunicode/tables.go", out.Bytes())
	out.Reset()
	fmt.Fprintln(&out, "// Code generated by scripts/generate-name-tables.go. DO NOT EDIT.\n// Derived from Apple's pinned UCStringCompareData.h; original license retained\n// in testdata/appledouble/native/name-comparison-source/UCStringCompareData.h.gz.\npackage hfsplus")
	body := regexp.MustCompile(`(?s)/\*.*?\*/`).ReplaceAllString(string(read(primary+"/UCStringCompareData.h.gz")), "")
	table := func(name string) []uint16 {
		_, x, ok := strings.Cut(body, name+"[] = {")
		if !ok {
			panic(name)
		}
		x, _, _ = strings.Cut(x, "}")
		var out []uint16
		for _, v := range regexp.MustCompile(`0x[0-9A-Fa-f]+`).FindAllString(x, -1) {
			out = append(out, uint16(parse(v[2:])))
		}
		return out
	}
	latin, lower := table("gLatinCaseFold"), table("gLowerCaseTable")
	if len(latin) != 256 {
		panic("Latin table")
	}
	fmt.Fprintln(&out, "var caseFold = map[uint16]uint16{")
	var ignored []int
	for n := 0; n <= 65535; n++ {
		f := uint16(n)
		if n < 256 {
			f = latin[n]
		} else if off := lower[n>>8]; off != 0 {
			f = lower[int(off)+(n&255)]
		}
		if f == 0 {
			ignored = append(ignored, n)
		} else if f != uint16(n) {
			fmt.Fprintf(&out, "0x%04X:0x%04X,\n", n, f)
		}
	}
	fmt.Fprintln(&out, "}\nvar caseFoldIgnored = map[uint16]bool{")
	for _, r := range ignored {
		fmt.Fprintf(&out, "0x%04X:true,\n", r)
	}
	fmt.Fprintln(&out, "}\nfunc foldUnit(u uint16)(uint16,bool){if caseFoldIgnored[u]{return 0,false};if f,ok:=caseFold[u];ok{return f,true};return u,true}")
	write("pkg/hfsplus/casefold_table.go", out.Bytes())
}
func keys[V any](m map[rune]V) []rune {
	k := make([]rune, 0, len(m))
	for r := range m {
		k = append(k, r)
	}
	sort.Slice(k, func(i, j int) bool { return k[i] < k[j] })
	return k
}
func writeMap(out *bytes.Buffer, name string, m map[rune]string) {
	fmt.Fprintf(out, "var %s = map[rune]string{\n", name)
	for _, r := range keys(m) {
		fmt.Fprintf(out, "0x%X:%q,\n", r, m[r])
	}
	fmt.Fprintln(out, "}")
}
func write(p string, b []byte) {
	b, e := format.Source(b)
	must(e)
	if *check {
		if !bytes.Equal(read(p), b) {
			panic("generated table differs: " + p)
		}
		return
	}
	must(os.MkdirAll(filepath.Dir(p), 0755))
	must(os.WriteFile(p, b, 0644))
}
