//go:build ignore

// Generate exact APFS creation-admission intervals from every native scalar.
package main

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"strings"

	"github.com/deploymenttheory/go-apfs-v2/internal/testutil/captureprovenance"
	"github.com/deploymenttheory/go-apfs-v2/pkg/osversion"
)

func must(e error) {
	if e != nil {
		panic(e)
	}
}
func hash(b []byte) string { h := sha256.Sum256(b); return hex.EncodeToString(h[:]) }
func main() {
	check := flag.Bool("check", false, "verify committed tables without writing")
	flag.Parse()
	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by scripts/generate-name-admission.go. DO NOT EDIT.\n// Every interval derives from actual native O_CREAT results, not Unicode age.\npackage nameunicode")
	for _, major := range []int{15, 26, 27} {
		p := fmt.Sprintf("testdata/appledouble/native/name-admission-macos%d.json.gz", major)
		raw, e := os.ReadFile(p)
		must(e)
		z, e := gzip.NewReader(bytes.NewReader(raw))
		must(e)
		var c struct {
			Host    string
			Schema  int
			Sources map[string]string
			Volumes []struct {
				Kind    string
				Results []byte
				Native  struct {
					Count  int `json:"scalar_count"`
					Counts map[int]int
				}
			}
		}
		plain, err := io.ReadAll(z)
		must(errors.Join(err, z.Close()))
		must(json.Unmarshal(plain, &c))
		must(requireAdmissionProfile(c.Host, major))
		if c.Schema != 1 || len(c.Volumes) != 2 {
			panic("native inventory")
		}
		reference, err := captureprovenance.Reference(os.DirFS("."), c.Sources)
		must(err)
		if err := captureprovenance.Verify(reference, c.Sources); err != nil {
			panic(err)
		}
		for p := range c.Sources {
			if strings.HasPrefix(p, "testdata/") || strings.HasPrefix(p, "scripts/") || strings.HasPrefix(p, ".github/") || p == "go.mod" || p == "go.sum" {
				_, e := captureprovenance.ReadSource(reference, c.Sources, p)
				must(e)
			}
		}
		a := c.Volumes[0]
		b := c.Volumes[1]
		if a.Kind != "APFS" || b.Kind != "APFSX" || a.Native.Count != 1112062 || b.Native.Count != 1112062 || len(a.Results) != 0x110000 || !bytes.Equal(a.Results, b.Results) {
			panic("native volume/scalar inventory")
		}
		counts := map[int]int{}
		for r, status := range a.Results {
			excluded := r == 0 || r == 47 || (r >= 0xd800 && r <= 0xdfff)
			if excluded {
				if status != 255 {
					panic("excluded scalar")
				}
				continue
			}
			if status != 0 && status != 92 {
				panic("unexpected native errno")
			}
			counts[int(status)]++
		}
		for status, n := range counts {
			if a.Native.Counts[status] != n || b.Native.Counts[status] != n {
				panic("native counts")
			}
		}
		// The table consumes the complete scalar result domain for this native
		// profile. Compiler, driver and module provenance stays in the immutable
		// capture ledger; it cannot change a table with identical native results.
		input := append([]byte(fmt.Sprintf("apfs-create-scalars-v1/macos%d\n", major)), a.Results...)
		fmt.Fprintf(&out, "// %s native scalar SHA256 %s\nvar apfsCreate%d = [...]scalarRange{\n", p, hash(input), major)
		for r := 0; r < len(a.Results); r++ {
			if a.Results[r] != 0 {
				continue
			}
			start := r
			for r+1 < len(a.Results) && a.Results[r+1] == 0 {
				r++
			}
			fmt.Fprintf(&out, "{0x%X,0x%X},\n", start, r)
		}
		fmt.Fprintln(&out, "}")
	}
	body, e := format.Source(out.Bytes())
	must(e)
	const dest = "internal/nameunicode/admission_tables.go"
	if *check {
		existing, err := os.ReadFile(dest)
		must(err)
		if !bytes.Equal(existing, body) {
			panic("generated admission table differs")
		}
		return
	}
	must(os.WriteFile(dest, body, 0644))
}

func requireAdmissionProfile(host string, expected int) error {
	profile, err := osversion.ParseProductVersion(host)
	if err != nil {
		return err
	}
	if _, err = osversion.ProfileForMacOS(profile); err != nil {
		return err
	}
	if int(profile.Major) != expected {
		return fmt.Errorf("native admission Host profile%d differs from filename%d", profile.Major, expected)
	}
	return nil
}
