// Code generated by go run scripts/generate-darwin-wrappers.go; DO NOT EDIT.
#include "textflag.h"

TEXT trampolineFcntlGetPath<>(SB),NOSPLIT,$0-0
	JMP importedFcntlGetPath(SB)
GLOBL ·addrFcntlGetPath(SB), RODATA, $8
DATA ·addrFcntlGetPath(SB)/8, $trampolineFcntlGetPath<>(SB)

TEXT trampolineFgetattrlist<>(SB),NOSPLIT,$0-0
	JMP importedFgetattrlist(SB)
GLOBL ·addrFgetattrlist(SB), RODATA, $8
DATA ·addrFgetattrlist(SB)/8, $trampolineFgetattrlist<>(SB)

TEXT trampolineGetattrlistat<>(SB),NOSPLIT,$0-0
	JMP importedGetattrlistat(SB)
GLOBL ·addrGetattrlistat(SB), RODATA, $8
DATA ·addrGetattrlistat(SB)/8, $trampolineGetattrlistat<>(SB)

TEXT trampolineListxattr<>(SB),NOSPLIT,$0-0
	JMP importedListxattr(SB)
GLOBL ·addrListxattr(SB), RODATA, $8
DATA ·addrListxattr(SB)/8, $trampolineListxattr<>(SB)

TEXT trampolineGetxattr<>(SB),NOSPLIT,$0-0
	JMP importedGetxattr(SB)
GLOBL ·addrGetxattr(SB), RODATA, $8
DATA ·addrGetxattr(SB)/8, $trampolineGetxattr<>(SB)

TEXT trampolineFlistxattr<>(SB),NOSPLIT,$0-0
	JMP importedFlistxattr(SB)
GLOBL ·addrFlistxattr(SB), RODATA, $8
DATA ·addrFlistxattr(SB)/8, $trampolineFlistxattr<>(SB)

TEXT trampolineFgetxattr<>(SB),NOSPLIT,$0-0
	JMP importedFgetxattr(SB)
GLOBL ·addrFgetxattr(SB), RODATA, $8
DATA ·addrFgetxattr(SB)/8, $trampolineFgetxattr<>(SB)

TEXT trampolineFilesecInit<>(SB),NOSPLIT,$0-0
	JMP importedFilesecInit(SB)
GLOBL ·addrFilesecInit(SB), RODATA, $8
DATA ·addrFilesecInit(SB)/8, $trampolineFilesecInit<>(SB)

TEXT trampolineFilesecFree<>(SB),NOSPLIT,$0-0
	JMP importedFilesecFree(SB)
GLOBL ·addrFilesecFree(SB), RODATA, $8
DATA ·addrFilesecFree(SB)/8, $trampolineFilesecFree<>(SB)

TEXT trampolineFilesecGetProperty<>(SB),NOSPLIT,$0-0
	JMP importedFilesecGetProperty(SB)
GLOBL ·addrFilesecGetProperty(SB), RODATA, $8
DATA ·addrFilesecGetProperty(SB)/8, $trampolineFilesecGetProperty<>(SB)

TEXT trampolineFstatx<>(SB),NOSPLIT,$0-0
	JMP importedFstatx(SB)
GLOBL ·addrFstatx(SB), RODATA, $8
DATA ·addrFstatx(SB)/8, $trampolineFstatx<>(SB)

TEXT trampolineFchmodExtended<>(SB),NOSPLIT,$0-0
	JMP importedFchmodExtended(SB)
GLOBL ·addrFchmodExtended(SB), RODATA, $8
DATA ·addrFchmodExtended(SB)/8, $trampolineFchmodExtended<>(SB)

TEXT trampolineFsetattrlist<>(SB),NOSPLIT,$0-0
	JMP importedFsetattrlist(SB)
GLOBL ·addrFsetattrlist(SB), RODATA, $8
DATA ·addrFsetattrlist(SB)/8, $trampolineFsetattrlist<>(SB)

TEXT trampolineFfsctl<>(SB),NOSPLIT,$0-0
	JMP importedFfsctl(SB)
GLOBL ·addrFfsctl(SB), RODATA, $8
DATA ·addrFfsctl(SB)/8, $trampolineFfsctl<>(SB)

TEXT trampolineStatx<>(SB),NOSPLIT,$0-0
	JMP importedStatx(SB)
GLOBL ·addrStatx(SB), RODATA, $8
DATA ·addrStatx(SB)/8, $trampolineStatx<>(SB)

TEXT trampolineLstatx<>(SB),NOSPLIT,$0-0
	JMP importedLstatx(SB)
GLOBL ·addrLstatx(SB), RODATA, $8
DATA ·addrLstatx(SB)/8, $trampolineLstatx<>(SB)

TEXT trampolineChmodExtended<>(SB),NOSPLIT,$0-0
	JMP importedChmodExtended(SB)
GLOBL ·addrChmodExtended(SB), RODATA, $8
DATA ·addrChmodExtended(SB)/8, $trampolineChmodExtended<>(SB)

TEXT trampolineOpenDprotected<>(SB),NOSPLIT,$0-0
	JMP importedOpenDprotected(SB)
GLOBL ·addrOpenDprotected(SB), RODATA, $8
DATA ·addrOpenDprotected(SB)/8, $trampolineOpenDprotected<>(SB)

TEXT trampolineMacSyscall<>(SB),NOSPLIT,$0-0
	JMP importedMacSyscall(SB)
GLOBL ·addrMacSyscall(SB), RODATA, $8
DATA ·addrMacSyscall(SB)/8, $trampolineMacSyscall<>(SB)

TEXT trampolineQuarantineProcessAlloc<>(SB),NOSPLIT,$0-0
	JMP importedQuarantineProcessAlloc(SB)
GLOBL ·addrQuarantineProcessAlloc(SB), RODATA, $8
DATA ·addrQuarantineProcessAlloc(SB)/8, $trampolineQuarantineProcessAlloc<>(SB)

TEXT trampolineQuarantineProcessFree<>(SB),NOSPLIT,$0-0
	JMP importedQuarantineProcessFree(SB)
GLOBL ·addrQuarantineProcessFree(SB), RODATA, $8
DATA ·addrQuarantineProcessFree(SB)/8, $trampolineQuarantineProcessFree<>(SB)

TEXT trampolineQuarantineProcessInit<>(SB),NOSPLIT,$0-0
	JMP importedQuarantineProcessInit(SB)
GLOBL ·addrQuarantineProcessInit(SB), RODATA, $8
DATA ·addrQuarantineProcessInit(SB)/8, $trampolineQuarantineProcessInit<>(SB)

TEXT trampolineAppSandboxed<>(SB),NOSPLIT,$0-0
	JMP importedAppSandboxed(SB)
GLOBL ·addrAppSandboxed(SB), RODATA, $8
DATA ·addrAppSandboxed(SB)/8, $trampolineAppSandboxed<>(SB)

TEXT trampolineGetpwuid<>(SB),NOSPLIT,$0-0
	JMP importedGetpwuid(SB)
GLOBL ·addrGetpwuid(SB), RODATA, $8
DATA ·addrGetpwuid(SB)/8, $trampolineGetpwuid<>(SB)

TEXT trampolineGetpwnam<>(SB),NOSPLIT,$0-0
	JMP importedGetpwnam(SB)
GLOBL ·addrGetpwnam(SB), RODATA, $8
DATA ·addrGetpwnam(SB)/8, $trampolineGetpwnam<>(SB)

TEXT trampolineGetgrgid<>(SB),NOSPLIT,$0-0
	JMP importedGetgrgid(SB)
GLOBL ·addrGetgrgid(SB), RODATA, $8
DATA ·addrGetgrgid(SB)/8, $trampolineGetgrgid<>(SB)

TEXT trampolineGetgrnam<>(SB),NOSPLIT,$0-0
	JMP importedGetgrnam(SB)
GLOBL ·addrGetgrnam(SB), RODATA, $8
DATA ·addrGetgrnam(SB)/8, $trampolineGetgrnam<>(SB)

TEXT trampolineUserUUID<>(SB),NOSPLIT,$0-0
	JMP importedUserUUID(SB)
GLOBL ·addrUserUUID(SB), RODATA, $8
DATA ·addrUserUUID(SB)/8, $trampolineUserUUID<>(SB)

TEXT trampolineGroupUUID<>(SB),NOSPLIT,$0-0
	JMP importedGroupUUID(SB)
GLOBL ·addrGroupUUID(SB), RODATA, $8
DATA ·addrGroupUUID(SB)/8, $trampolineGroupUUID<>(SB)

TEXT trampolineUUIDIdentity<>(SB),NOSPLIT,$0-0
	JMP importedUUIDIdentity(SB)
GLOBL ·addrUUIDIdentity(SB), RODATA, $8
DATA ·addrUUIDIdentity(SB)/8, $trampolineUUIDIdentity<>(SB)
