// Code generated by go run scripts/generate-darwin-wrappers.go; DO NOT EDIT.
//go:build darwin && amd64

package darwinabi

import (
	"unsafe"

	"golang.org/x/sys/unix"
)

// FcntlGetPath is the typed fcntl wrapper.
//
//go:uintptrescapes
func FcntlGetPath(fd int32, path *[unix.PathMax]byte) (int32, error) {
	r, _, e := syscall3(addrFcntlGetPath, uintptr(fd), uintptr(unix.F_GETPATH), uintptr(unsafe.Pointer(path)))
	if e != 0 {
		return int32(r), e
	}
	return int32(r), nil
}

var addrFcntlGetPath uintptr

//go:cgo_import_dynamic importedFcntlGetPath fcntl "/usr/lib/libSystem.B.dylib"

// Getattrlistat is the typed getattrlistat wrapper.
//
//go:uintptrescapes
func Getattrlistat(fd int32, path *byte, attributes *unix.Attrlist, data unsafe.Pointer, size uintptr, options uint64) (int32, error) {
	r, _, e := syscall6(addrGetattrlistat, uintptr(fd), uintptr(unsafe.Pointer(path)), uintptr(unsafe.Pointer(attributes)), uintptr(data), size, uintptr(options))
	if e != 0 {
		return int32(r), e
	}
	return int32(r), nil
}

var addrGetattrlistat uintptr

//go:cgo_import_dynamic importedGetattrlistat getattrlistat "/usr/lib/libSystem.B.dylib"

// Listxattr is the typed listxattr wrapper.
//
//go:uintptrescapes
func Listxattr(path, data *byte, size uintptr, options int32) (int64, error) {
	r, _, e := syscall6X(addrListxattr, uintptr(unsafe.Pointer(path)), uintptr(unsafe.Pointer(data)), size, uintptr(options), 0, 0)
	if e != 0 {
		return 0, e
	}
	return int64(r), nil
}

var addrListxattr uintptr

//go:cgo_import_dynamic importedListxattr listxattr "/usr/lib/libSystem.B.dylib"

// Getxattr is the typed getxattr wrapper.
//
//go:uintptrescapes
func Getxattr(path, name, data *byte, size uintptr, position uint32, options int32) (int64, error) {
	r, _, e := syscall6X(addrGetxattr, uintptr(unsafe.Pointer(path)), uintptr(unsafe.Pointer(name)), uintptr(unsafe.Pointer(data)), size, uintptr(position), uintptr(options))
	if e != 0 {
		return 0, e
	}
	return int64(r), nil
}

var addrGetxattr uintptr

//go:cgo_import_dynamic importedGetxattr getxattr "/usr/lib/libSystem.B.dylib"

// Flistxattr is the typed flistxattr wrapper.
//
//go:uintptrescapes
func Flistxattr(fd int32, data *byte, size uintptr, options int32) (int64, error) {
	r, _, e := syscall6X(addrFlistxattr, uintptr(fd), uintptr(unsafe.Pointer(data)), size, uintptr(options), 0, 0)
	if e != 0 {
		return 0, e
	}
	return int64(r), nil
}

var addrFlistxattr uintptr

//go:cgo_import_dynamic importedFlistxattr flistxattr "/usr/lib/libSystem.B.dylib"

// Fgetxattr is the typed fgetxattr wrapper.
//
//go:uintptrescapes
func Fgetxattr(fd int32, name, data *byte, size uintptr, position uint32, options int32) (int64, error) {
	r, _, e := syscall6X(addrFgetxattr, uintptr(fd), uintptr(unsafe.Pointer(name)), uintptr(unsafe.Pointer(data)), size, uintptr(position), uintptr(options))
	if e != 0 {
		return 0, e
	}
	return int64(r), nil
}

var addrFgetxattr uintptr

//go:cgo_import_dynamic importedFgetxattr fgetxattr "/usr/lib/libSystem.B.dylib"

// FilesecInit is the typed filesec_init wrapper.
//
//go:uintptrescapes
func FilesecInit() uintptr {
	r, _, _ := syscall6X(addrFilesecInit, 0, 0, 0, 0, 0, 0)
	return r
}

var addrFilesecInit uintptr

//go:cgo_import_dynamic importedFilesecInit filesec_init "/usr/lib/libSystem.B.dylib"

// FilesecFree is the typed filesec_free wrapper.
//
//go:uintptrescapes
func FilesecFree(security uintptr) {
	_, _, _ = syscall6(addrFilesecFree, security, 0, 0, 0, 0, 0)

}

var addrFilesecFree uintptr

//go:cgo_import_dynamic importedFilesecFree filesec_free "/usr/lib/libSystem.B.dylib"

// FilesecGetProperty is the typed filesec_get_property wrapper.
//
//go:uintptrescapes
func FilesecGetProperty(security uintptr, property int32, output unsafe.Pointer) (int32, error) {
	r, _, e := syscall6(addrFilesecGetProperty, security, uintptr(property), uintptr(output), 0, 0, 0)
	if e != 0 {
		return int32(r), e
	}
	return int32(r), nil
}

var addrFilesecGetProperty uintptr

//go:cgo_import_dynamic importedFilesecGetProperty filesec_get_property "/usr/lib/libSystem.B.dylib"

// Fstatx is the typed fstatx_np wrapper.
//
//go:uintptrescapes
func Fstatx(fd int32, stat *unix.Stat_t, security uintptr) (int32, error) {
	r, _, e := syscall6(addrFstatx, uintptr(fd), uintptr(unsafe.Pointer(stat)), security, 0, 0, 0)
	if e != 0 {
		return int32(r), e
	}
	return int32(r), nil
}

var addrFstatx uintptr

//go:cgo_import_dynamic importedFstatx fstatx_np$INODE64 "/usr/lib/libSystem.B.dylib"

// FchmodExtended is the typed __fchmod_extended wrapper.
//
//go:uintptrescapes
func FchmodExtended(fd int32, uid, gid uint32, mode int32, security uintptr) (int32, error) {
	r, _, e := syscall6(addrFchmodExtended, uintptr(fd), uintptr(uid), uintptr(gid), uintptr(mode), security, 0)
	if e != 0 {
		return int32(r), e
	}
	return int32(r), nil
}

var addrFchmodExtended uintptr

//go:cgo_import_dynamic importedFchmodExtended __fchmod_extended "/usr/lib/libSystem.B.dylib"

// Fsetattrlist is the typed fsetattrlist wrapper.
//
//go:uintptrescapes
func Fsetattrlist(fd int32, attributes *unix.Attrlist, data unsafe.Pointer, size uintptr, options uint32) (int32, error) {
	r, _, e := syscall6(addrFsetattrlist, uintptr(fd), uintptr(unsafe.Pointer(attributes)), uintptr(data), size, uintptr(options), 0)
	if e != 0 {
		return int32(r), e
	}
	return int32(r), nil
}

var addrFsetattrlist uintptr

//go:cgo_import_dynamic importedFsetattrlist fsetattrlist "/usr/lib/libSystem.B.dylib"

// Ffsctl is the typed ffsctl wrapper.
//
//go:uintptrescapes
func Ffsctl(fd int32, command uintptr, data unsafe.Pointer, options uint32) (int32, error) {
	r, _, e := syscall6(addrFfsctl, uintptr(fd), command, uintptr(data), uintptr(options), 0, 0)
	if e != 0 {
		return int32(r), e
	}
	return int32(r), nil
}

var addrFfsctl uintptr

//go:cgo_import_dynamic importedFfsctl ffsctl "/usr/lib/libSystem.B.dylib"

// Statx is the typed statx_np wrapper.
//
//go:uintptrescapes
func Statx(path *byte, stat *unix.Stat_t, security uintptr) (int32, error) {
	r, _, e := syscall6(addrStatx, uintptr(unsafe.Pointer(path)), uintptr(unsafe.Pointer(stat)), security, 0, 0, 0)
	if e != 0 {
		return int32(r), e
	}
	return int32(r), nil
}

var addrStatx uintptr

//go:cgo_import_dynamic importedStatx statx_np$INODE64 "/usr/lib/libSystem.B.dylib"

// Lstatx is the typed lstatx_np wrapper.
//
//go:uintptrescapes
func Lstatx(path *byte, stat *unix.Stat_t, security uintptr) (int32, error) {
	r, _, e := syscall6(addrLstatx, uintptr(unsafe.Pointer(path)), uintptr(unsafe.Pointer(stat)), security, 0, 0, 0)
	if e != 0 {
		return int32(r), e
	}
	return int32(r), nil
}

var addrLstatx uintptr

//go:cgo_import_dynamic importedLstatx lstatx_np$INODE64 "/usr/lib/libSystem.B.dylib"

// ChmodExtended is the typed __chmod_extended wrapper.
//
//go:uintptrescapes
func ChmodExtended(path *byte, uid, gid uint32, mode int32, security uintptr) (int32, error) {
	r, _, e := syscall6(addrChmodExtended, uintptr(unsafe.Pointer(path)), uintptr(uid), uintptr(gid), uintptr(mode), security, 0)
	if e != 0 {
		return int32(r), e
	}
	return int32(r), nil
}

var addrChmodExtended uintptr

//go:cgo_import_dynamic importedChmodExtended __chmod_extended "/usr/lib/libSystem.B.dylib"

// OpenDprotected is the typed __open_dprotected_np wrapper.
//
//go:uintptrescapes
func OpenDprotected(path *byte, flags, class, dpflags int32, mode uint32) (int32, error) {
	r, _, e := syscall6(addrOpenDprotected, uintptr(unsafe.Pointer(path)), uintptr(flags), uintptr(class), uintptr(dpflags), uintptr(mode), 0)
	if e != 0 {
		return int32(r), e
	}
	return int32(r), nil
}

var addrOpenDprotected uintptr

//go:cgo_import_dynamic importedOpenDprotected __open_dprotected_np "/usr/lib/libSystem.B.dylib"

// MacSyscall is the typed __mac_syscall wrapper.
//
//go:uintptrescapes
func MacSyscall(policy *byte, operation int32, data unsafe.Pointer) (int32, error) {
	r, _, e := syscall6(addrMacSyscall, uintptr(unsafe.Pointer(policy)), uintptr(operation), uintptr(data), 0, 0, 0)
	if e != 0 {
		return int32(r), e
	}
	return int32(r), nil
}

var addrMacSyscall uintptr

//go:cgo_import_dynamic importedMacSyscall __mac_syscall "/usr/lib/libSystem.B.dylib"

// QuarantineProcessAlloc is the typed _qtn_proc_alloc wrapper.
//
//go:uintptrescapes
func QuarantineProcessAlloc() uintptr {
	r, _, _ := syscall6X(addrQuarantineProcessAlloc, 0, 0, 0, 0, 0, 0)
	return r
}

var addrQuarantineProcessAlloc uintptr

//go:cgo_import_dynamic importedQuarantineProcessAlloc _qtn_proc_alloc "/usr/lib/system/libquarantine.dylib"

// QuarantineProcessFree is the typed _qtn_proc_free wrapper.
//
//go:uintptrescapes
func QuarantineProcessFree(process uintptr) {
	_, _, _ = syscall6(addrQuarantineProcessFree, process, 0, 0, 0, 0, 0)

}

var addrQuarantineProcessFree uintptr

//go:cgo_import_dynamic importedQuarantineProcessFree _qtn_proc_free "/usr/lib/system/libquarantine.dylib"

// QuarantineProcessInit is the typed _qtn_proc_init_with_self wrapper.
//
//go:uintptrescapes
func QuarantineProcessInit(process uintptr) (int32, error) {
	r, _, e := syscall6(addrQuarantineProcessInit, process, 0, 0, 0, 0, 0)
	if e != 0 {
		return int32(r), e
	}
	return int32(r), nil
}

var addrQuarantineProcessInit uintptr

//go:cgo_import_dynamic importedQuarantineProcessInit _qtn_proc_init_with_self "/usr/lib/system/libquarantine.dylib"

// AppSandboxed is the typed _xpc_runtime_is_app_sandboxed wrapper.
//
//go:uintptrescapes
func AppSandboxed() bool {
	r, _, _ := syscall6(addrAppSandboxed, 0, 0, 0, 0, 0, 0)
	return byte(r) != 0
}

var addrAppSandboxed uintptr

//go:cgo_import_dynamic importedAppSandboxed _xpc_runtime_is_app_sandboxed "/usr/lib/system/libxpc.dylib"

// Getpwuid is the typed getpwuid_r wrapper.
//
//go:uintptrescapes
func Getpwuid(id uint32, record *Passwd, buffer *byte, size uintptr, result **Passwd) int32 {
	r, _, _ := syscall6(addrGetpwuid, uintptr(id), uintptr(unsafe.Pointer(record)), uintptr(unsafe.Pointer(buffer)), size, uintptr(unsafe.Pointer(result)), 0)
	return int32(r)
}

var addrGetpwuid uintptr

//go:cgo_import_dynamic importedGetpwuid getpwuid_r "/usr/lib/libSystem.B.dylib"

// Getpwnam is the typed getpwnam_r wrapper.
//
//go:uintptrescapes
func Getpwnam(name *byte, record *Passwd, buffer *byte, size uintptr, result **Passwd) int32 {
	r, _, _ := syscall6(addrGetpwnam, uintptr(unsafe.Pointer(name)), uintptr(unsafe.Pointer(record)), uintptr(unsafe.Pointer(buffer)), size, uintptr(unsafe.Pointer(result)), 0)
	return int32(r)
}

var addrGetpwnam uintptr

//go:cgo_import_dynamic importedGetpwnam getpwnam_r "/usr/lib/libSystem.B.dylib"

// Getgrgid is the typed getgrgid_r wrapper.
//
//go:uintptrescapes
func Getgrgid(id uint32, record *Group, buffer *byte, size uintptr, result **Group) int32 {
	r, _, _ := syscall6(addrGetgrgid, uintptr(id), uintptr(unsafe.Pointer(record)), uintptr(unsafe.Pointer(buffer)), size, uintptr(unsafe.Pointer(result)), 0)
	return int32(r)
}

var addrGetgrgid uintptr

//go:cgo_import_dynamic importedGetgrgid getgrgid_r "/usr/lib/libSystem.B.dylib"

// Getgrnam is the typed getgrnam_r wrapper.
//
//go:uintptrescapes
func Getgrnam(name *byte, record *Group, buffer *byte, size uintptr, result **Group) int32 {
	r, _, _ := syscall6(addrGetgrnam, uintptr(unsafe.Pointer(name)), uintptr(unsafe.Pointer(record)), uintptr(unsafe.Pointer(buffer)), size, uintptr(unsafe.Pointer(result)), 0)
	return int32(r)
}

var addrGetgrnam uintptr

//go:cgo_import_dynamic importedGetgrnam getgrnam_r "/usr/lib/libSystem.B.dylib"

// UserUUID is the typed mbr_uid_to_uuid wrapper.
//
//go:uintptrescapes
func UserUUID(id uint32, uuid *[16]byte) int32 {
	r, _, _ := syscall6(addrUserUUID, uintptr(id), uintptr(unsafe.Pointer(uuid)), 0, 0, 0, 0)
	return int32(r)
}

var addrUserUUID uintptr

//go:cgo_import_dynamic importedUserUUID mbr_uid_to_uuid "/usr/lib/libSystem.B.dylib"

// GroupUUID is the typed mbr_gid_to_uuid wrapper.
//
//go:uintptrescapes
func GroupUUID(id uint32, uuid *[16]byte) int32 {
	r, _, _ := syscall6(addrGroupUUID, uintptr(id), uintptr(unsafe.Pointer(uuid)), 0, 0, 0, 0)
	return int32(r)
}

var addrGroupUUID uintptr

//go:cgo_import_dynamic importedGroupUUID mbr_gid_to_uuid "/usr/lib/libSystem.B.dylib"

// UUIDIdentity is the typed mbr_uuid_to_id wrapper.
//
//go:uintptrescapes
func UUIDIdentity(uuid *[16]byte, id *uint32, kind *int32) int32 {
	r, _, _ := syscall6(addrUUIDIdentity, uintptr(unsafe.Pointer(uuid)), uintptr(unsafe.Pointer(id)), uintptr(unsafe.Pointer(kind)), 0, 0, 0)
	return int32(r)
}

var addrUUIDIdentity uintptr

//go:cgo_import_dynamic importedUUIDIdentity mbr_uuid_to_id "/usr/lib/libSystem.B.dylib"
